[package]
name = "srml-slashing"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
parity-codec = { version = "4.1.1", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
system = { package = "srml-system", path = "../system", default-features = false }
srml-staking = { package = "srml-staking", path = "../staking", default-features = false }
srml-support = { path = "../support", default-features = false }
primitives = { package = "sr-primitives", path = "../../core/sr-primitives", default-features = false }

[dev-dependencies]
substrate-primitives = { path = "../../core/primitives" }
balances = { package = "srml-balances", path = "../balances" }
session = { package = "srml-session", path = "../session", default-features = false }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"rstd/std",
	"srml-staking/std",
	"srml-support/std",
	"primitives/std",
	"system/std",
]
